# Generated by Django 3.2.7 on 2021-09-22 22:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TripCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_date', models.DateTimeField(auto_now_add=True, help_text='Date  time on record was created', verbose_name='Created on')),
                ('write_date', models.DateTimeField(auto_now=True, help_text='Date  time on record was last modified', verbose_name='Created on')),
                ('name', models.CharField(max_length=120, verbose_name='Categoría')),
                ('slug', models.SlugField(verbose_name='Etiqueta')),
            ],
            options={
                'ordering': ('-create_date', '-write_date'),
                'abstract': False,
            },
        ),
    ]
