# Generated by Django 3.2.7 on 2021-09-22 23:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='tripcategory',
            options={'verbose_name': 'Categoría de viajes', 'verbose_name_plural': 'Categorías de viajes'},
        ),
    ]
