# Generated by Django 3.2.7 on 2021-09-23 13:28

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_date', models.DateTimeField(auto_now_add=True, help_text='Date  time on record was created', verbose_name='Created on')),
                ('write_date', models.DateTimeField(auto_now=True, help_text='Date  time on record was last modified', verbose_name='Created on')),
                ('picture', models.ImageField(blank=True, null=True, upload_to='users/pictures/', verbose_name='Profile picture')),
                ('biography', models.TextField(blank=True, max_length=500, verbose_name='Biography')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='User')),
            ],
            options={
                'ordering': ('-create_date', '-write_date'),
                'abstract': False,
            },
        ),
    ]
